name: Feature Branch Validation

on:
  push:
    branches:
      - 'feature/**'

permissions:
  id-token: write
  contents: read

jobs:
  validate:
    uses: divyasingh0/az_tf_workflow/.github/workflows/terraform_pr.yml@main

    with:
      environment: dev
      working_directory: .

    secrets: inherit